Repository yourssu-Lab/iOS-ssumgo, pull requests merged in 2024-11, with the labels that each got.

#6 [Setting] Pretendard 폰트 세팅
  iOS-ssumgo/iOS-ssumgo.xcodeproj/project.pbxproj
  iOS-ssumgo/iOS-ssumgo/Info.plist
  iOS-ssumgo/iOS-ssumgo/Resource/Extension/SwiftUI+/UIFont+.swift
  iOS-ssumgo/iOS-ssumgo/Resource/Fonts/Pretendard-Black.otf
  iOS-ssumgo/iOS-ssumgo/Resource/Fonts/Pretendard-Bold.otf
  iOS-ssumgo/iOS-ssumgo/Resource/Fonts/Pretendard-ExtraBold.otf
  iOS-ssumgo/iOS-ssumgo/Resource/Fonts/Pretendard-ExtraLight.otf
  iOS-ssumgo/iOS-ssumgo/Resource/Fonts/Pretendard-Light.otf
  iOS-ssumgo/iOS-ssumgo/Resource/Fonts/Pretendard-Medium.otf
  iOS-ssumgo/iOS-ssumgo/Resource/Fonts/Pretendard-Regular.otf
  iOS-ssumgo/iOS-ssumgo/Resource/Fonts/Pretendard-SemiBold.otf
  iOS-ssumgo/iOS-ssumgo/Resource/Fonts/Pretendard-Thin.otf
Labels: Setting ⚙, Mai 🌻

#12 [Feat] ssumgoMain 페이지 레이아웃 구현
  iOS-ssumgo/.DS_Store
  iOS-ssumgo/iOS-ssumgo/Application/iOS_ssumgoApp.swift
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/.DS_Store
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/color/s_banner_green.colorset/Contents.json
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/icon/.DS_Store
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/.DS_Store
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_computer.imageset/Contents.json
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_computer.imageset/img_computer@1x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_computer.imageset/img_computer@2x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_computer.imageset/img_computer@3x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumg.imageset/숭실숨고로고 1.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumg.imageset/숭실숨고로고 2.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumg.imageset/숭실숨고로고 3.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumgo.imageset/Contents.json
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumgo.imageset/숭실숨고로고@1x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumgo.imageset/숭실숨고로고@2x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumgo.imageset/숭실숨고로고@3x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_media.imageset/Contents.json
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_media.imageset/img_media@1x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_media.imageset/img_media@2x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_media.imageset/img_media@3x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_programming.imageset/Contents.json
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_programming.imageset/img_programming@1x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_programming.imageset/img_programming@2x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_programming.imageset/img_programming@3x.png
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Home/View/AnswersView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Home/View/BannerView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Home/View/SsumgoMainView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Home/View/SubjectView.swift
Labels: Feature ✨, Tom 🍀

#9 [Feat] CustomBoxButton, 스플래쉬 뷰 구현
  iOS-ssumgo/iOS-ssumgo/Resource/UIComponents/Button/CustomBoxButton.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Splash/View/SplashView.swift
Labels: Feature ✨, Mai 🌻

#13 [Feat] 마이페이지 UI 구현
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/CustomTabBar/CustomTabBarView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Mypage/MyPageView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Mypage/View/MyPageView.swift
Labels: Feature ✨, Mai 🌻

#15 [Feat] 로고 네비게이션 바, 로그인 뷰 UI 구현
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumg.imageset/Contents.json
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumg.imageset/숭실숨고로고@1x 1.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumg.imageset/숭실숨고로고@2x 1.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumg.imageset/숭실숨고로고@3x 1.png
  iOS-ssumgo/iOS-ssumgo/Resource/UIComponents/NavigationBar/LogoNavigationBar.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Login/View/LoginView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Login/ViewModel/LoginViewModel.swift
Labels: Feature ✨, Mai 🌻

#20 [Feat] SsumgoMainView 로고 네비게이션, 커스텀 탭바 적용
  iOS-ssumgo/.DS_Store
  iOS-ssumgo/iOS-ssumgo/Application/iOS_ssumgoApp.swift
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumg.imageset/Contents.json
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumg.imageset/숭실숨고로고 dd1 3.png
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/CustomTabBar/CustomTabBarView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Home/View/SsumgoMainView.swift
Labels: Design 🎨, Feature ✨, Tom 🍀

#18 [Feat] notificationMentee 페이지UI 구현
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Notification/NotificationListView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Notification/NotificationView.swift
Labels: Feature ✨, Tom 🍀

#22 [Feat] 빈 알림 페이지 구현
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Notification/NotificationView.swift
Labels: Feature ✨, Tom 🍀

#26 [Rename] Notification의 하위 폴더 View 생성
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Notification/View/NotificationListView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Notification/View/NotificationView.swift
Labels: Tom 🍀

#30 [Feat] #29 Student 관련 API 연결
  .gitignore
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumg.imageset/Contents.json
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumg.imageset/숭실숨고로고 dd1 4.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumg.imageset/숭실숨고로고 dd1 5.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/img_logo_ssumg.imageset/숭실숨고로고 dd1 6.png
  iOS-ssumgo/iOS-ssumgo/Source/Common/DAO/LoginDAO.swift
  iOS-ssumgo/iOS-ssumgo/Source/Common/DAO/MyPageDAO.swift
  iOS-ssumgo/iOS-ssumgo/Source/Common/DTO/LoginDTO.swift
  iOS-ssumgo/iOS-ssumgo/Source/Common/DTO/ProfileDTO.swift
  iOS-ssumgo/iOS-ssumgo/Source/Network/Base/APIError.swift
  iOS-ssumgo/iOS-ssumgo/Source/Network/Base/BaseAPIClient.swift
  iOS-ssumgo/iOS-ssumgo/Source/Network/Base/BaseResponse.swift
  iOS-ssumgo/iOS-ssumgo/Source/Network/Base/HTTPMethod.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Login/View/LoginView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Login/ViewModel/LoginViewModel.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Mypage/View/MyPageView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Mypage/ViewModel/MyPageViewModel.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Splash/View/SplashView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Splash/ViewModel/SplashViewModel.swift
Labels: API 📬, Mai 🌻

#33 [Feat] SsumgoMainView API연결
  iOS-ssumgo/.DS_Store
  iOS-ssumgo/iOS-ssumgo.xcodeproj/project.pbxproj
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/Banner/Banner1.imageset/Banner1@1x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/Banner/Banner1.imageset/Banner1@2x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/Banner/Banner1.imageset/Banner1@3x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/Banner/Banner1.imageset/Contents.json
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/Banner/Banner2.imageset/Banner2@1x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/Banner/Banner2.imageset/Banner2@2x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/Banner/Banner2.imageset/Banner2@3x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/Banner/Banner2.imageset/Contents.json
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/Banner/Banner3.imageset/Banner3@1x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/Banner/Banner3.imageset/Banner3@2x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/Banner/Banner3.imageset/Banner3@3x.png
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/Banner/Banner3.imageset/Contents.json
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/image/Banner/Contents.json
  iOS-ssumgo/iOS-ssumgo/Source/Common/DAO/SubjectsInquiryDAO.swift
  iOS-ssumgo/iOS-ssumgo/Source/Common/DTO/SubjectsInquiryDTO.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Home/View/AnswersView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Home/View/BannerView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Home/View/SsumgoMainView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Home/View/SubjectView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Home/ViewModel/SsumgoMainViewModel.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Notification/View/NotificationView.swift
Labels: API 📬, Tom 🍀

#40 [Fix] #39 리프레시 토큰 요청 API 수정
  iOS-ssumgo/iOS-ssumgo/Source/Network/Base/APIError.swift
  iOS-ssumgo/iOS-ssumgo/Source/Network/Base/BaseAPIClient.swift
Labels: API 📬, Mai 🌻

#41 [Feat] 이용약관 페이지 구현
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/TermsOfService/View/TermsOfServiceView.swift
Labels: Design 🎨, Mai 🌻

#43 [Feat] CustomCircleButton 구현
  iOS-ssumgo/iOS-ssumgo/Resource/Assets.xcassets/color/s_gray_button.colorset/Contents.json
  iOS-ssumgo/iOS-ssumgo/Resource/UIComponents/Button/CustomCircleButton.swift
Labels: Feature ✨, Mai 🌻

#45 [Feat] CustomAccordionButton 구현
  iOS-ssumgo/iOS-ssumgo/Resource/UIComponents/Button/CustomAccordionButton.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Chat/ChatView.swift
Labels: Feature ✨, Mai 🌻

#48 [Feat] PostWrite 질문 등록 APi 연결
  iOS-ssumgo/iOS-ssumgo/Source/Common/DAO/PostWriteDAO.swift
  iOS-ssumgo/iOS-ssumgo/Source/Common/DTO/PostWriteDTO.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Home/View/SsumgoMainView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Home/View/SubjectView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Home/ViewModel/SsumgoMainViewModel.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/PostWrite/View/PostWriteView.swift
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/PostWrite/ViewModel/PostWriteViewModel.swift
Labels: Feature ✨, API 📬, Tom 🍀

#50 [Feat] 알림페이지 더미데이터로 채움, 모두읽기 기능추가
  iOS-ssumgo/iOS-ssumgo/Source/Presentation/Notification/View/NotificationView.swift
Labels: Feature ✨, Tom 🍀
